"""empty message

Revision ID: 87628c530e53
Revises: 868efeba0246
Create Date: 2024-05-19 14:44:09.991896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87628c530e53'
down_revision = '868efeba0246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn=op.get_bind()
    inspector=sa.inspect(conn)
    columns=[col['name'] for col in inspector.get_columns('items')]
    with op.batch_alter_table('items', schema=None) as batch_op:
        if 'description' not in columns:
            batch_op.add_column(sa.Column('description', sa.String(), nullable=True))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
